version: '3.4'
services:
  db:
    image: mysql:8.0.23
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_calculadora
    ports:
      - "3308:3306"
    networks:
      - udemy-network
  api:
    image: rodrigofranco91/rest-with-spring-boot-udemy
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /api-rest
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - udemy-network
networks:
    udemy-network:
        driver: bridge
