version: '3.4'
services:
  db:
    image: rodrigofranco91/mysql-rest-with-spring-boot-udemy
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: ./bd
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_calculadora
    ports:
      - "3308:3306"
    networks:
      - udemy-network
  api:
    image: rodrigofranco91/rest-with-spring-boot-udemy
    restart: always
    build: ./api
    working_dir: /api-rest
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ~/eclipse-workspace/RestAPI-SpringBoot-AWS-Docker:/api-rest
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - udemy-network
networks:
    udemy-network:
        driver: bridge
